export const USER_ROLES = {
  SUPERADMIN: 'superadmin',
  ADMIN: 'admin',
  STAFF: 'staff',
  MEMBER: 'member',
} as const;

export const ROLE_PERMISSIONS = {
  superadmin: {
    canViewAllData: true,
    canCreateAdmins: true,
    canDeleteAdmins: true,
    canCreateMembers: true,
    canEditMembers: true,
    canDeleteMembers: true,
    canCreateProducts: true,
    canEditProducts: true,
    canDeleteProducts: true,
    canCreateExpenses: true,
    canEditExpenses: true,
    canDeleteExpenses: true,
    canCreatePromos: true,
    canEditPromos: true,
    canDeletePromos: true,
    canApproveEdits: true,
    canViewAnalytics: true,
    canExportData: true,
    canManageRoles: true,
  },
  admin: {
    canViewAllData: true,
    canCreateAdmins: false,
    canDeleteAdmins: false,
    canCreateMembers: true,
    canEditMembers: true,
    canDeleteMembers: true,
    canCreateProducts: true,
    canEditProducts: true,
    canDeleteProducts: true,
    canCreateExpenses: true,
    canEditExpenses: true,
    canDeleteExpenses: true,
    canCreatePromos: true,
    canEditPromos: true,
    canDeletePromos: true,
    canApproveEdits: true,
    canViewAnalytics: true,
    canExportData: true,
    canManageRoles: false,
  },
  staff: {
    canViewAllData: false,
    canCreateMembers: false,
    canEditMembers: false,
    canDeleteMembers: false,
    canCreateProducts: false,
    canEditProducts: false,
    canDeleteProducts: false,
    canCreateExpenses: true,
    canEditExpenses: false,
    canDeleteExpenses: false,
    canCreatePromos: false,
    canEditPromos: false,
    canDeletePromos: false,
    canApproveEdits: false,
    canLogCustomers: true,
    canViewShiftBalance: true,
  },
  member: {
    canViewProfile: true,
    canEditProfile: true,
    canViewPromos: true,
    canViewMembership: true,
  },
} as const;
